DROP TABLE IF EXISTS Prepare;
DROP TABLE IF EXISTS Ordered_By;
DROP TABLE IF EXISTS Food_Order;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Cook;
DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Cuisine;

CREATE TABLE IF NOT EXISTS Cuisine (
    name VARCHAR(256) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Item (
    name     VARCHAR(256) PRIMARY KEY,
    price    NUMERIC NOT NULL CHECK (price > 0),
    cuisine  VARCHAR(256) NOT NULL,
    FOREIGN KEY (cuisine) REFERENCES Cuisine(name) ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED 
);

CREATE TABLE IF NOT EXISTS Staff (
    id    VARCHAR(256) PRIMARY KEY,
    name  VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS Cook (
    staff    VARCHAR(256) REFERENCES Staff(id) ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    cuisine  VARCHAR(256) REFERENCES Cuisine(name) ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    PRIMARY KEY (staff, cuisine)
);

CREATE TABLE IF NOT EXISTS Member (
    phone      INTEGER PRIMARY KEY,
    firstname  VARCHAR(256) NOT NULL,
    lastname   VARCHAR(256) NOT NULL,
    reg_date   DATE NOT NULL,
	reg_time   TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Food_Order (
    id    VARCHAR(256) PRIMARY KEY,
    date  DATE NOT NULL,
    time  TIME NOT NULL,
    payment_method VARCHAR(10) NOT NULL,
    card         VARCHAR(256),
    card_type    VARCHAR(256),
    CHECK (
        (payment_method = 'card' AND card IS NOT NULL AND card_type IS NOT NULL)
            OR
        (payment_method = 'cash' AND card IS NULL AND card_type IS NULL)
    ),
    total_price NUMERIC NOT NULL DEFAULT 0 CHECK (total_price >= 0)
);

CREATE TABLE IF NOT EXISTS Ordered_By (
    order_id    VARCHAR(256) PRIMARY KEY REFERENCES Food_Order(id) DEFERRABLE INITIALLY DEFERRED,
    member      INTEGER NOT NULL REFERENCES Member(phone) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS Prepare (
    order_id  VARCHAR(256) REFERENCES Food_Order(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    item      VARCHAR(256) REFERENCES Item(name) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    staff     VARCHAR(256) REFERENCES Staff(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    qty       INT NOT NULL CHECK (qty > 0),
    PRIMARY KEY (order_id, item, staff)
);
